{
  "formatVersion": "1.1",
  "component": {
    "group": "ToastTransformProject",
    "module": "lib",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lib-unspecified.jar",
          "url": "lib-unspecified.jar",
          "size": 629,
          "sha512": "b8e28988ee36e7132129ae6cafe343847fe7811c7684aa655d6303fad2ad1fbeeddd32b51b8ef35ba58043d3069a164fdc51d83a77afb5213e9edff6563162a4",
          "sha256": "472b7f698e90b395afb425eeb9c9d00dc56432dcd3833dd2631707dea0fde58c",
          "sha1": "73ed3a5cd3b3ab5cfe5cbc19cef96b08c0b91bff",
          "md5": "c175c55acd7ce3ffec36ddeb0bc61736"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.22.0-GA"
          }
        }
      ],
      "files": [
        {
          "name": "lib-unspecified.jar",
          "url": "lib-unspecified.jar",
          "size": 629,
          "sha512": "b8e28988ee36e7132129ae6cafe343847fe7811c7684aa655d6303fad2ad1fbeeddd32b51b8ef35ba58043d3069a164fdc51d83a77afb5213e9edff6563162a4",
          "sha256": "472b7f698e90b395afb425eeb9c9d00dc56432dcd3833dd2631707dea0fde58c",
          "sha1": "73ed3a5cd3b3ab5cfe5cbc19cef96b08c0b91bff",
          "md5": "c175c55acd7ce3ffec36ddeb0bc61736"
        }
      ]
    }
  ]
}
