{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yechaoa.plugin",
    "module": "lib2",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "dependencies-1.0.0.jar",
          "url": "dependencies-1.0.0.jar",
          "size": 2146,
          "sha512": "388e98a18ecb59be9fe0c62a47d6ae0c13c70b707f7e95c2337ad5fe9939a9ebe50cf3902888c17c3eec755bb3d7ec6b653d9f1509c397293ae2f8aebe7b0627",
          "sha256": "74f128e2111edfdd13027e90874ed09c3c12810f51b8c96e52baabd5f811f54b",
          "sha1": "860f86de7c8106064b615cd5c495d70ec0a7ebbd",
          "md5": "aad50f5e6f3d4702490f2123483eb921"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "dependencies-1.0.0.jar",
          "url": "dependencies-1.0.0.jar",
          "size": 2146,
          "sha512": "388e98a18ecb59be9fe0c62a47d6ae0c13c70b707f7e95c2337ad5fe9939a9ebe50cf3902888c17c3eec755bb3d7ec6b653d9f1509c397293ae2f8aebe7b0627",
          "sha256": "74f128e2111edfdd13027e90874ed09c3c12810f51b8c96e52baabd5f811f54b",
          "sha1": "860f86de7c8106064b615cd5c495d70ec0a7ebbd",
          "md5": "aad50f5e6f3d4702490f2123483eb921"
        }
      ]
    }
  ]
}
