{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yechaoa.plugin",
    "module": "lib2",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lib2-1.0.0.jar",
          "url": "lib2-1.0.0.jar",
          "size": 12381,
          "sha512": "7844e1d82e44e375e1fc0361b5672528752b49c11f50780072853369eb1637080f89649920be6fcc8c68ec73d7a573120d83fa5148b4eabc404744a5fa708e01",
          "sha256": "fae34f27a8fd31e170d2d04b11a91704223f53de672d9ad73f1602221b1572d3",
          "sha1": "6f55afd10160df18faea68dbcfcd930d4a098863",
          "md5": "754b1a4462d4548f11e16ae4cd1ffe5b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.22.0-GA"
          }
        }
      ],
      "files": [
        {
          "name": "lib2-1.0.0.jar",
          "url": "lib2-1.0.0.jar",
          "size": 12381,
          "sha512": "7844e1d82e44e375e1fc0361b5672528752b49c11f50780072853369eb1637080f89649920be6fcc8c68ec73d7a573120d83fa5148b4eabc404744a5fa708e01",
          "sha256": "fae34f27a8fd31e170d2d04b11a91704223f53de672d9ad73f1602221b1572d3",
          "sha1": "6f55afd10160df18faea68dbcfcd930d4a098863",
          "md5": "754b1a4462d4548f11e16ae4cd1ffe5b"
        }
      ]
    }
  ]
}
